
services:

  coguweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2522:8000  # port du server : port de l'application
    volumes:
      - .:/cogu-app/
      - static_volume:/cogu-app/staticfiles
      - media_volume:/cogu-app/mediafiles
    env_file:
      - ./.env
    restart: always
    depends_on:
      - coguDB

  coguDB:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
#    networks:
#      - cogu_default

  adminer:
    image: adminer
    restart: always
    ports:
      - 2310:8080
#    networks:
#      - cogu_default

#networks:
#  cogu_default:

volumes:
  pgdata:
    driver: local
  static_volume:
  media_volume: