# Generated by Django 4.2.20 on 2025-04-07 22:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('civilite', models.CharField(blank=True, choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Docteur', 'Docteur'), ('Professeur', 'Professeur'), ('Excellence', 'Excellence'), ('Honorable', 'Honorable')], max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction', models.CharField(blank=True, max_length=255, null=True)),
                ('roleemployee', models.CharField(choices=[('National', 'National'), ('Regional', 'Régional'), ('DistrictSanitaire', 'District Sanitaire'), ('CentreAntirabique', 'Centre Antirabique')], default='CentreAntirabique', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('Commune', 'Commune'), ('Village', 'Village'), ('Ville', 'Ville'), ('Quartier', 'Quartier')], max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=100, null=True)),
                ('is_in', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MajorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PolygonField(geography=True, help_text='Zone couverte par l’événement', srid=4326)),
                ('organizer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PolesRegionaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanitaryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('number_of_people_involved', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('mort', 'Décès'), ('blessure', 'Blessure'), ('sauvé', 'Sauvé'), ('autre', 'Autre')], max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Si l’incident est lié à un événement majeur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.majorevent')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogu.incidenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(blank=True, db_index=True, editable=False, max_length=225, unique=True)),
                ('mpi_upi', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('nom', models.CharField(db_index=True, max_length=225)),
                ('prenoms', models.CharField(db_index=True, max_length=225)),
                ('contact', models.CharField(db_index=True, max_length=20)),
                ('date_naissance', models.DateField(db_index=True)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Féminin')], max_length=10)),
                ('num_cmu', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cni_num', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cni_nni', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=200, null=True)),
                ('niveau_etude', models.CharField(blank=True, choices=[('Non scolarisé', 'Non scolarisé'), ('Préscolaire', 'Préscolaire'), ('Primaire', 'Primaire'), ('Secondaire', 'Secondaire'), ('Supérieur', 'Supérieur')], max_length=500, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('autretypeanimal', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_mineur', models.BooleanField(default=False)),
                ('accompagnateur', models.CharField(blank=True, max_length=255, null=True)),
                ('accompagnateur_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('accompagnateur_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('accompagnateur_nature', models.CharField(blank=True, choices=[('Pere', 'Pere'), ('Mere', 'Mere'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Frère', 'Frère'), ('Soeure', 'Soeure'), ('Cousin', 'Cousin'), ('Cousine', 'Cousine'), ('Connaissance du quartier', 'Connaissance du quartier'), ('Voisin du quartier', 'Voisin du quartier'), ('Propriétaire animal ', 'Propriétaire animal ')], max_length=255, null=True)),
                ('accompagnateur_niveau_etude', models.CharField(blank=True, choices=[('Non scolarisé', 'Non scolarisé'), ('Préscolaire', 'Préscolaire'), ('Primaire', 'Primaire'), ('Secondaire', 'Secondaire'), ('Supérieur', 'Supérieur')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Admis', 'Admis'), ('Sorti', 'Sorti'), ('Transféré', 'Transféré'), ('Décédé', 'Décédé'), ('Sous observation', 'Sous observation'), ('Sous traitement', 'Sous traitement'), ('Chirurgie programmée', 'Chirurgie programmée'), ('En chirurgie', 'En chirurgie'), ('Récupération post-opératoire', 'Récupération post-opératoire'), ('USI', 'Unité de soins intensifs (USI)'), ('Urgence', 'Urgence'), ('Consultation externe', 'Consultation externe'), ('Réhabilitation', 'Réhabilitation'), ('En attente de diagnostic', 'En attente de diagnostic'), ('Traitement en cours', 'Traitement en cours'), ('Suivi programmé', 'Suivi programmé'), ('Consultation', 'Consultation'), ('Sortie en attente', 'Sortie en attente'), ('Isolement', 'Isolement'), ('Ambulantoire', 'Ambulantoire'), ('Aucun', 'Aucun')], default='Aucun', max_length=100, null=True)),
                ('gueris', models.BooleanField(default=False)),
                ('decede', models.BooleanField(default=False)),
                ('cause_deces', models.TextField(blank=True, null=True)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('voir_patient', 'Peut voir patient'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code_patient', models.CharField(blank=True, db_index=True, editable=False, max_length=225)),
                ('mpi_upi', models.UUIDField(blank=True, db_index=True, null=True)),
                ('nom', models.CharField(db_index=True, max_length=225)),
                ('prenoms', models.CharField(db_index=True, max_length=225)),
                ('contact', models.CharField(db_index=True, max_length=20)),
                ('date_naissance', models.DateField(db_index=True)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Féminin')], max_length=10)),
                ('num_cmu', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cni_num', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('cni_nni', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=200, null=True)),
                ('niveau_etude', models.CharField(blank=True, choices=[('Non scolarisé', 'Non scolarisé'), ('Préscolaire', 'Préscolaire'), ('Primaire', 'Primaire'), ('Secondaire', 'Secondaire'), ('Supérieur', 'Supérieur')], max_length=500, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('autretypeanimal', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_mineur', models.BooleanField(default=False)),
                ('accompagnateur', models.CharField(blank=True, max_length=255, null=True)),
                ('accompagnateur_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('accompagnateur_adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('accompagnateur_nature', models.CharField(blank=True, choices=[('Pere', 'Pere'), ('Mere', 'Mere'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Frère', 'Frère'), ('Soeure', 'Soeure'), ('Cousin', 'Cousin'), ('Cousine', 'Cousine'), ('Connaissance du quartier', 'Connaissance du quartier'), ('Voisin du quartier', 'Voisin du quartier'), ('Propriétaire animal ', 'Propriétaire animal ')], max_length=255, null=True)),
                ('accompagnateur_niveau_etude', models.CharField(blank=True, choices=[('Non scolarisé', 'Non scolarisé'), ('Préscolaire', 'Préscolaire'), ('Primaire', 'Primaire'), ('Secondaire', 'Secondaire'), ('Supérieur', 'Supérieur')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Admis', 'Admis'), ('Sorti', 'Sorti'), ('Transféré', 'Transféré'), ('Décédé', 'Décédé'), ('Sous observation', 'Sous observation'), ('Sous traitement', 'Sous traitement'), ('Chirurgie programmée', 'Chirurgie programmée'), ('En chirurgie', 'En chirurgie'), ('Récupération post-opératoire', 'Récupération post-opératoire'), ('USI', 'Unité de soins intensifs (USI)'), ('Urgence', 'Urgence'), ('Consultation externe', 'Consultation externe'), ('Réhabilitation', 'Réhabilitation'), ('En attente de diagnostic', 'En attente de diagnostic'), ('Traitement en cours', 'Traitement en cours'), ('Suivi programmé', 'Suivi programmé'), ('Consultation', 'Consultation'), ('Sortie en attente', 'Sortie en attente'), ('Isolement', 'Isolement'), ('Ambulantoire', 'Ambulantoire'), ('Aucun', 'Aucun')], default='Aucun', max_length=100, null=True)),
                ('gueris', models.BooleanField(default=False)),
                ('decede', models.BooleanField(default=False)),
                ('cause_deces', models.TextField(blank=True, null=True)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('commune', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cogu.commune')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical patient',
                'verbose_name_plural': 'historical patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HealthRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('poles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='cogu.polesregionaux')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('geom', djgeojson.fields.PointField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='cogu.healthregion')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogu.districtsanitaire'),
        ),
    ]
