# Generated by Django 4.2.20 on 2025-04-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanitaryincident',
            name='region',
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.incidenttype'),
        ),
        migrations.AddField(
            model_name='majorevent',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.majorevent'),
        ),
        migrations.AddField(
            model_name='sanitaryincident',
            name='patients_related',
            field=models.ManyToManyField(db_index=True, to='cogu.patient'),
        ),
        migrations.AlterField(
            model_name='sanitaryincident',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.commune'),
        ),
    ]
