# Generated by Django 4.2.20 on 2025-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitaryincident',
            name='evacues_nbr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanitaryincident',
            name='exeat_nbr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanitaryincident',
            name='pris_en_charge_nbr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sanitaryincident',
            name='outcome',
            field=models.CharField(choices=[('mort', 'Décès'), ('blessure', 'Blessure'), ('sauvé', 'Sauvé'), ('exeat', 'Exeat'), ('evacue', 'Évacué'), ('pris_charge', 'Pris en charge'), ('autre', 'Autre')], db_index=True, max_length=100),
        ),
    ]
