# Generated by Django 4.2.20 on 2025-04-22 20:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0002_sanitaryincident_evacues_nbr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposantKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('code_produit', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unite_mesure', models.CharField(choices=[('unite', 'Unité'), ('boite', 'Boîte'), ('carton', 'Carton'), ('kg', 'Kilogramme'), ('litre', 'Litre')], max_length=20)),
                ('duree_conservation', models.PositiveIntegerField(help_text='Durée en mois avant péremption', validators=[django.core.validators.MinValueValidator(1)])),
                ('temperature_stockage', models.CharField(default='Ambiance', help_text='Conditions de stockage recommandées', max_length=50)),
                ('seuil_alerte', models.PositiveIntegerField(default=10, help_text='Seuil minimum pour déclencher une alerte')),
            ],
            options={
                'verbose_name': 'Composant de kit',
                'verbose_name_plural': 'Composants de kits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code_fournisseur', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text="Instructions d'utilisation")),
                ('capacite_personnes', models.PositiveIntegerField(default=1, help_text='Nombre de personnes que le kit peut couvrir')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Kit d'urgence",
                'verbose_name_plural': "Kits d'urgence",
                'ordering': ['categorie', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='KitCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('niveau_urgence', models.CharField(choices=[('routine', 'Routine'), ('urgence', 'Urgence'), ('critique', 'Critique')], default='urgence', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de kit',
                'verbose_name_plural': 'Catégories de kits',
                'ordering': ['niveau_urgence', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='StockCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('capacite_max', models.PositiveIntegerField(help_text='Capacité totale en unités de stockage')),
                ('temperature_controlee', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cogu.servicesanitaire')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centres_responsables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centre de stockage',
                'verbose_name_plural': 'Centres de stockage',
                'ordering': ['region', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert', 'Transfert'), ('ajustement', 'Ajustement'), ('perte', 'Perte')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('centre_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrees', to='cogu.stockcentre')),
                ('centre_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorties', to='cogu.stockcentre')),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='cogu.composantkit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, help_text='Si lié à un incident sanitaire', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.sanitaryincident')),
                ('kit', models.ForeignKey(blank=True, help_text='Si lié à un kit spécifique', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.kit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KitComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_standard', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogu.composantkit')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='cogu.kit')),
            ],
            options={
                'verbose_name': 'Composition de kit',
                'verbose_name_plural': 'Compositions de kits',
                'unique_together': {('kit', 'composant')},
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cogu.kitcategorie'),
        ),
        migrations.AddField(
            model_name='kit',
            name='composants',
            field=models.ManyToManyField(related_name='kits', through='cogu.KitComposition', to='cogu.composantkit'),
        ),
        migrations.AddField(
            model_name='kit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DeploiementKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_envoi', models.DateTimeField()),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('preparation', 'En préparation'), ('envoye', 'Envoyé'), ('recu', 'Reçu'), ('utilise', 'Utilisé'), ('retourne', 'Retourné'), ('perdu', 'Perdu')], default='preparation', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois', to='cogu.stockcentre')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cogu.districtsanitaire')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_deployes', to='cogu.sanitaryincident')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deploiements', to='cogu.kit')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deploiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déploiement de kit',
                'verbose_name_plural': 'Déploiements de kits',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('lot', models.CharField(blank=True, max_length=50)),
                ('date_expiration', models.DateField()),
                ('date_reception', models.DateField(default=django.utils.timezone.now)),
                ('fournisseur', models.CharField(blank=True, max_length=100)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='cogu.stockcentre')),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='cogu.composantkit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['composant', 'date_expiration'],
                'unique_together': {('centre', 'composant', 'lot')},
            },
        ),
    ]
