# Generated by Django 4.2.20 on 2025-04-09 13:54

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0002_remove_sanitaryincident_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitaryincident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('role', models.CharField(max_length=255, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Intervenant',
                'verbose_name_plural': 'Intervenants',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la ressource')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogu.commune', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='Date du rapport')),
                ('details', models.TextField(verbose_name='Détails')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogu.sanitaryincident', verbose_name='Incident sanitaire')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.respondent', verbose_name='Intervenant')),
            ],
            options={
                'verbose_name': "Rapport d'incident",
                'verbose_name_plural': "Rapports d'incidents",
            },
        ),
    ]
