# Generated by Django 4.2.20 on 2025-04-22 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0003_composantkit_fournisseur_kit_kitcategorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogu.servicesanitaire'),
        ),
    ]
