# Generated by Django 4.2.20 on 2025-04-10 10:57

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0003_alter_sanitaryincident_location_respondent_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('upstream', models.CharField(blank=True, max_length=255, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('completeness', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('what3words', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogu.commune')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Reçu'), ('out', 'Envoyé')], max_length=3)),
                ('sender', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VictimCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prise_en_charge_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_prise_en_charge', models.CharField(choices=[('soins', 'Soins médicaux'), ('hospitalisation', 'Hospitalisation'), ('vaccination', 'Vaccination'), ('psy', 'Soutien psychologique'), ('financier', 'Soutien Financier'), ('autre', 'Autre')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lieu_prise_en_charge', models.CharField(blank=True, max_length=255)),
                ('intervenant', models.CharField(blank=True, max_length=255)),
                ('est_prise_en_charge_effective', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_cares', to='cogu.sanitaryincident')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cares', to='cogu.patient')),
                ('servicedesante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.servicesanitaire')),
            ],
        ),
        migrations.CreateModel(
            name='CareFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en cours', 'En cours'), ('terminé', 'Terminé'), ('référé', 'Référé'), ('non suivi', 'Non suivi')], max_length=100)),
                ('note', models.TextField(blank=True)),
                ('professionnel', models.CharField(blank=True, max_length=255)),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='cogu.victimcare')),
            ],
        ),
    ]
