# Generated by Django 4.2.20 on 2025-04-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0004_servicesanitaire_whatsappmessage_victimcare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_media/')),
                ('media_type', models.CharField(max_length=50)),
                ('original_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cogu.sanitaryincident')),
            ],
        ),
    ]
