# Generated by Django 4.2.20 on 2025-04-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0004_employeeuser_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='composantkit',
            name='kit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogu.kitcategorie'),
        ),
    ]
