# Generated by Django 4.2.20 on 2025-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0005_incidentmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentmedia',
            old_name='original_url',
            new_name='media_url',
        ),
        migrations.RemoveField(
            model_name='incidentmedia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incidentmedia',
            name='file',
        ),
        migrations.AddField(
            model_name='incidentmedia',
            name='downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='incident_media/'),
        ),
    ]
