# Generated by Django 4.2.20 on 2025-04-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0006_rename_original_url_incidentmedia_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitaryincident',
            name='status',
            field=models.CharField(choices=[('pending', 'À valider'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
