# Generated by Django 4.2.20 on 2025-04-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0007_sanitaryincident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorevent',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
