# Generated by Django 4.2.20 on 2025-04-11 20:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0008_majorevent_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorevent',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='Zone couverte par l’événement', null=True, srid=4326),
        ),
    ]
