# Generated by Django 4.2.20 on 2025-04-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0009_alter_majorevent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitaryincident',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Message WhatsApp à l’origine de l’incident, s’il y en a un', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='cogu.whatsappmessage'),
        ),
    ]
