# Generated by Django 4.2.20 on 2025-04-12 14:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0010_sanitaryincident_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmedia',
            name='downloaded_file',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='incident_media/'),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='media_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='media_url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sanitaryincident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sanitaryincident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sanitaryincident',
            name='status',
            field=models.CharField(choices=[('pending', 'À valider'), ('validated', 'Validé'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='body',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='direction',
            field=models.CharField(choices=[('in', 'Reçu'), ('out', 'Envoyé')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
