# Generated by Django 4.2.20 on 2025-04-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0012_sanitaryincident_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='photo',
            field=models.ImageField(blank=True, default='/static/assets/media/users/default.jpg', null=True, upload_to='users/images/'),
        ),
    ]
