# Generated by Django 4.2.20 on 2025-04-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0014_alter_employeeuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='photo',
            field=models.ImageField(blank=True, default='media/users/images/user.webp', null=True, upload_to='users/images/'),
        ),
    ]
