# Generated by Django 4.2.20 on 2025-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogu', '0016_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
